org.gradle.configuration-cache=true
org.gradle.console=verbose
org.gradle.jvmargs=-Xms16G -Xmx32G -XX:MaxMetaspaceSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.daemon.idletimeout=12800000

mavenCentralPublishing=true
signAllPublications=true