[versions]
guava = "33.4.6-jre"
junit-jupiter = "5.12.1"
mavencentral = "0.36.0"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[plugins]
mavencentral = { id = "com.vanniktech.maven.publish", version.ref = "mavencentral" }
